const mongoose = require('mongoose');
const University = require('../models/University');
const Scholarship = require('../models/Scholarship');
require('dotenv').config();

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/eduglobalbd', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
.then(() => console.log('MongoDB connected for seeding'))
.catch(err => console.error('MongoDB connection error:', err));

const scholarshipData = [
  // Bangladesh Universities
  {
    name: "BUET Merit Scholarship",
    country: "Bangladesh",
    city: "Dhaka",
    degreeLevel: "UG",
    fields: ["Engineering", "Computer Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.5,
    coveragePercent: 100,
    amountBDT: 500000,
    stipendMonthlyBDT: 15000,
    applicationFeeBDT: 0,
    deadline: new Date('2024-06-15'),
    rolling: false,
    description: "Full tuition waiver for top engineering students at BUET",
    isActive: true
  },
  {
    name: "DU Vice Chancellor's Scholarship",
    country: "Bangladesh",
    city: "Dhaka",
    degreeLevel: "Masters",
    fields: ["Arts", "Science", "Business"],
    meritBased: true,
    needBased: true,
    minGPA: 3.2,
    incomeMaxBDT: 500000,
    coveragePercent: 75,
    amountBDT: 300000,
    stipendMonthlyBDT: 12000,
    applicationFeeBDT: 1000,
    deadline: new Date('2024-07-20'),
    rolling: false,
    description: "Merit-cum-need scholarship for postgraduate students",
    isActive: true
  },
  {
    name: "NSU Excellence Award",
    country: "Bangladesh",
    city: "Dhaka",
    degreeLevel: "UG",
    fields: ["Business", "Engineering", "Computer Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.7,
    ieltsMin: 6.5,
    coveragePercent: 50,
    amountBDT: 400000,
    applicationFeeBDT: 2000,
    deadline: new Date('2024-08-10'),
    rolling: false,
    description: "Partial scholarship for high-achieving students",
    isActive: true
  },
  {
    name: "BRAC University Need-Based Aid",
    country: "Bangladesh",
    city: "Dhaka",
    degreeLevel: "UG",
    fields: ["Business", "Engineering", "Liberal Arts"],
    meritBased: false,
    needBased: true,
    minGPA: 2.8,
    incomeMaxBDT: 300000,
    coveragePercent: 80,
    amountBDT: 350000,
    stipendMonthlyBDT: 8000,
    applicationFeeBDT: 500,
    rolling: true,
    description: "Financial assistance for economically disadvantaged students",
    isActive: true
  },
  
  // Canadian Universities
  {
    name: "University of Toronto International Scholarship",
    country: "Canada",
    city: "Toronto",
    degreeLevel: "UG",
    fields: ["Engineering", "Computer Science", "Medicine"],
    meritBased: true,
    needBased: false,
    minGPA: 3.8,
    ieltsMin: 7.0,
    toeflMin: 100,
    coveragePercent: 100,
    amountBDT: 4500000,
    stipendMonthlyBDT: 120000,
    applicationFeeBDT: 8500,
    deadline: new Date('2024-12-01'),
    rolling: false,
    description: "Full scholarship for exceptional international students",
    isActive: true
  },
  {
    name: "McGill Entrance Scholarship",
    country: "Canada",
    city: "Montreal",
    degreeLevel: "UG",
    fields: ["Science", "Arts", "Engineering"],
    meritBased: true,
    needBased: false,
    minGPA: 3.6,
    ieltsMin: 6.5,
    toeflMin: 90,
    coveragePercent: 75,
    amountBDT: 3200000,
    applicationFeeBDT: 9000,
    deadline: new Date('2024-11-15'),
    rolling: false,
    description: "Renewable scholarship for outstanding students",
    isActive: true
  },
  {
    name: "UBC International Leader of Tomorrow Award",
    country: "Canada",
    city: "Vancouver",
    degreeLevel: "UG",
    fields: ["Business", "Science", "Arts"],
    meritBased: true,
    needBased: true,
    minGPA: 3.5,
    incomeMaxBDT: 1200000,
    ieltsMin: 6.5,
    toeflMin: 90,
    coveragePercent: 100,
    amountBDT: 4200000,
    stipendMonthlyBDT: 100000,
    applicationFeeBDT: 8000,
    deadline: new Date('2024-12-15'),
    rolling: false,
    description: "Full scholarship for future leaders with financial need",
    isActive: true
  },
  {
    name: "Waterloo Engineering Excellence Scholarship",
    country: "Canada",
    city: "Waterloo",
    degreeLevel: "UG",
    fields: ["Engineering", "Computer Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.7,
    ieltsMin: 7.0,
    toeflMin: 100,
    coveragePercent: 60,
    amountBDT: 2800000,
    applicationFeeBDT: 7500,
    deadline: new Date('2024-10-30'),
    rolling: false,
    description: "Merit scholarship for engineering students",
    isActive: true
  },
  {
    name: "York University International Scholarship",
    country: "Canada",
    city: "Toronto",
    degreeLevel: "Masters",
    fields: ["Business", "Arts", "Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.4,
    ieltsMin: 6.5,
    toeflMin: 83,
    coveragePercent: 50,
    amountBDT: 1800000,
    applicationFeeBDT: 6000,
    deadline: new Date('2024-09-20'),
    rolling: false,
    description: "Partial funding for international graduate students",
    isActive: true
  },
  
  // UK Universities
  {
    name: "Oxford Reach Scholarship",
    country: "UK",
    city: "Oxford",
    degreeLevel: "UG",
    fields: ["Arts", "Science", "Medicine"],
    meritBased: true,
    needBased: true,
    minGPA: 3.9,
    incomeMaxBDT: 800000,
    ieltsMin: 7.5,
    toeflMin: 110,
    coveragePercent: 100,
    amountBDT: 5500000,
    stipendMonthlyBDT: 150000,
    applicationFeeBDT: 12000,
    deadline: new Date('2024-10-15'),
    rolling: false,
    description: "Full scholarship for exceptional students from developing countries",
    isActive: true
  },
  {
    name: "Cambridge International Scholarship",
    country: "UK",
    city: "Cambridge",
    degreeLevel: "PhD",
    fields: ["Science", "Engineering", "Medicine"],
    meritBased: true,
    needBased: false,
    minGPA: 3.8,
    ieltsMin: 7.5,
    toeflMin: 110,
    greMin: 320,
    coveragePercent: 100,
    amountBDT: 6000000,
    stipendMonthlyBDT: 180000,
    applicationFeeBDT: 15000,
    deadline: new Date('2024-12-01'),
    rolling: false,
    description: "Full PhD funding including living expenses",
    isActive: true
  },
  {
    name: "Imperial College London Scholarship",
    country: "UK",
    city: "London",
    degreeLevel: "Masters",
    fields: ["Engineering", "Science", "Medicine"],
    meritBased: true,
    needBased: false,
    minGPA: 3.6,
    ieltsMin: 7.0,
    toeflMin: 100,
    coveragePercent: 75,
    amountBDT: 4200000,
    applicationFeeBDT: 10000,
    deadline: new Date('2024-11-30'),
    rolling: false,
    description: "Partial scholarship for STEM postgraduate students",
    isActive: true
  },
  {
    name: "UCL Global Excellence Scholarship",
    country: "UK",
    city: "London",
    degreeLevel: "UG",
    fields: ["Arts", "Science", "Engineering"],
    meritBased: true,
    needBased: false,
    minGPA: 3.7,
    ieltsMin: 6.5,
    toeflMin: 92,
    coveragePercent: 50,
    amountBDT: 2800000,
    applicationFeeBDT: 8000,
    deadline: new Date('2024-09-15'),
    rolling: false,
    description: "Merit-based scholarship for international undergraduates",
    isActive: true
  },
  {
    name: "Edinburgh Global Research Scholarship",
    country: "UK",
    city: "Edinburgh",
    degreeLevel: "PhD",
    fields: ["Science", "Arts", "Engineering"],
    meritBased: true,
    needBased: false,
    minGPA: 3.5,
    ieltsMin: 7.0,
    toeflMin: 100,
    greMin: 310,
    coveragePercent: 100,
    amountBDT: 5200000,
    stipendMonthlyBDT: 160000,
    applicationFeeBDT: 12000,
    deadline: new Date('2024-10-31'),
    rolling: false,
    description: "Full PhD scholarship with research stipend",
    isActive: true
  },
  
  // USA Universities
  {
    name: "Harvard Need-Based Aid",
    country: "USA",
    city: "Cambridge",
    degreeLevel: "UG",
    fields: ["Arts", "Science", "Engineering"],
    meritBased: false,
    needBased: true,
    minGPA: 3.5,
    incomeMaxBDT: 1500000,
    ieltsMin: 7.5,
    toeflMin: 110,
    coveragePercent: 100,
    amountBDT: 7500000,
    stipendMonthlyBDT: 200000,
    applicationFeeBDT: 20000,
    deadline: new Date('2024-11-01'),
    rolling: false,
    description: "Full financial aid for students with demonstrated need",
    isActive: true
  },
  {
    name: "MIT International Science Scholarship",
    country: "USA",
    city: "Cambridge",
    degreeLevel: "UG",
    fields: ["Engineering", "Computer Science", "Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.9,
    ieltsMin: 7.5,
    toeflMin: 110,
    coveragePercent: 100,
    amountBDT: 8000000,
    stipendMonthlyBDT: 180000,
    applicationFeeBDT: 18000,
    deadline: new Date('2024-12-15'),
    rolling: false,
    description: "Full scholarship for exceptional STEM students",
    isActive: true
  },
  {
    name: "Stanford Knight-Hennessy Scholars",
    country: "USA",
    city: "Stanford",
    degreeLevel: "Masters",
    fields: ["Business", "Engineering", "Medicine"],
    meritBased: true,
    needBased: false,
    minGPA: 3.8,
    ieltsMin: 7.0,
    toeflMin: 100,
    greMin: 320,
    coveragePercent: 100,
    amountBDT: 7200000,
    stipendMonthlyBDT: 220000,
    applicationFeeBDT: 15000,
    deadline: new Date('2024-10-10'),
    rolling: false,
    description: "Full funding for graduate studies with leadership development",
    isActive: true
  },
  {
    name: "UC Berkeley International Scholarship",
    country: "USA",
    city: "Berkeley",
    degreeLevel: "UG",
    fields: ["Engineering", "Science", "Arts"],
    meritBased: true,
    needBased: true,
    minGPA: 3.6,
    incomeMaxBDT: 1000000,
    ieltsMin: 6.5,
    toeflMin: 90,
    coveragePercent: 80,
    amountBDT: 5500000,
    applicationFeeBDT: 12000,
    deadline: new Date('2024-11-30'),
    rolling: false,
    description: "Substantial aid for high-achieving international students",
    isActive: true
  },
  {
    name: "NYU Global Scholarship",
    country: "USA",
    city: "New York",
    degreeLevel: "Masters",
    fields: ["Business", "Arts", "Engineering"],
    meritBased: true,
    needBased: false,
    minGPA: 3.4,
    ieltsMin: 6.5,
    toeflMin: 90,
    coveragePercent: 60,
    amountBDT: 4200000,
    applicationFeeBDT: 10000,
    deadline: new Date('2024-09-30'),
    rolling: false,
    description: "Partial scholarship for international graduate students",
    isActive: true
  },
  
  // Australian Universities
  {
    name: "Australia Awards Scholarship",
    country: "Australia",
    city: "Melbourne",
    degreeLevel: "Masters",
    fields: ["Engineering", "Science", "Business"],
    meritBased: true,
    needBased: true,
    minGPA: 3.2,
    incomeMaxBDT: 800000,
    ieltsMin: 6.5,
    toeflMin: 79,
    coveragePercent: 100,
    amountBDT: 4800000,
    stipendMonthlyBDT: 140000,
    applicationFeeBDT: 0,
    deadline: new Date('2024-08-30'),
    rolling: false,
    description: "Government scholarship for developing country students",
    isActive: true
  },
  {
    name: "University of Sydney International Scholarship",
    country: "Australia",
    city: "Sydney",
    degreeLevel: "UG",
    fields: ["Business", "Engineering", "Medicine"],
    meritBased: true,
    needBased: false,
    minGPA: 3.7,
    ieltsMin: 7.0,
    toeflMin: 96,
    coveragePercent: 75,
    amountBDT: 3600000,
    applicationFeeBDT: 8000,
    deadline: new Date('2024-10-15'),
    rolling: false,
    description: "Merit scholarship for high-achieving international students",
    isActive: true
  },
  {
    name: "ANU Chancellor's International Scholarship",
    country: "Australia",
    city: "Canberra",
    degreeLevel: "PhD",
    fields: ["Science", "Engineering", "Arts"],
    meritBased: true,
    needBased: false,
    minGPA: 3.6,
    ieltsMin: 6.5,
    toeflMin: 80,
    greMin: 310,
    coveragePercent: 100,
    amountBDT: 4500000,
    stipendMonthlyBDT: 150000,
    applicationFeeBDT: 6000,
    deadline: new Date('2024-12-31'),
    rolling: false,
    description: "Full PhD scholarship with living allowance",
    isActive: true
  },
  {
    name: "Monash International Merit Scholarship",
    country: "Australia",
    city: "Melbourne",
    degreeLevel: "UG",
    fields: ["Engineering", "Science", "Business"],
    meritBased: true,
    needBased: false,
    minGPA: 3.5,
    ieltsMin: 6.5,
    toeflMin: 79,
    coveragePercent: 50,
    amountBDT: 2400000,
    applicationFeeBDT: 7000,
    deadline: new Date('2024-09-15'),
    rolling: false,
    description: "Partial tuition scholarship for international students",
    isActive: true
  },
  
  // German Universities
  {
    name: "DAAD Scholarship",
    country: "Germany",
    city: "Berlin",
    degreeLevel: "Masters",
    fields: ["Engineering", "Science", "Arts"],
    meritBased: true,
    needBased: false,
    minGPA: 3.3,
    ieltsMin: 6.5,
    toeflMin: 87,
    coveragePercent: 100,
    amountBDT: 3200000,
    stipendMonthlyBDT: 95000,
    applicationFeeBDT: 0,
    deadline: new Date('2024-11-15'),
    rolling: false,
    description: "Full scholarship from German Academic Exchange Service",
    isActive: true
  },
  {
    name: "TUM International Scholarship",
    country: "Germany",
    city: "Munich",
    degreeLevel: "UG",
    fields: ["Engineering", "Computer Science", "Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.6,
    ieltsMin: 6.5,
    toeflMin: 88,
    coveragePercent: 80,
    amountBDT: 2800000,
    applicationFeeBDT: 5000,
    deadline: new Date('2024-07-31'),
    rolling: false,
    description: "Merit scholarship for international engineering students",
    isActive: true
  },
  {
    name: "Heidelberg University Excellence Scholarship",
    country: "Germany",
    city: "Heidelberg",
    degreeLevel: "PhD",
    fields: ["Science", "Medicine", "Arts"],
    meritBased: true,
    needBased: false,
    minGPA: 3.7,
    ieltsMin: 7.0,
    toeflMin: 95,
    greMin: 315,
    coveragePercent: 100,
    amountBDT: 3800000,
    stipendMonthlyBDT: 120000,
    applicationFeeBDT: 3000,
    deadline: new Date('2024-12-15'),
    rolling: false,
    description: "Full PhD funding with research stipend",
    isActive: true
  },
  
  // Malaysian Universities
  {
    name: "University of Malaya International Scholarship",
    country: "Malaysia",
    city: "Kuala Lumpur",
    degreeLevel: "Masters",
    fields: ["Engineering", "Business", "Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.2,
    ieltsMin: 6.0,
    toeflMin: 80,
    coveragePercent: 100,
    amountBDT: 1800000,
    stipendMonthlyBDT: 45000,
    applicationFeeBDT: 2000,
    deadline: new Date('2024-08-15'),
    rolling: false,
    description: "Full scholarship for international postgraduate students",
    isActive: true
  },
  {
    name: "UTM International Doctoral Fellowship",
    country: "Malaysia",
    city: "Johor Bahru",
    degreeLevel: "PhD",
    fields: ["Engineering", "Science", "Technology"],
    meritBased: true,
    needBased: false,
    minGPA: 3.5,
    ieltsMin: 6.0,
    toeflMin: 80,
    coveragePercent: 100,
    amountBDT: 2200000,
    stipendMonthlyBDT: 55000,
    applicationFeeBDT: 1500,
    deadline: new Date('2024-09-30'),
    rolling: false,
    description: "Full PhD scholarship with monthly allowance",
    isActive: true
  },
  {
    name: "UCSI Merit Scholarship",
    country: "Malaysia",
    city: "Kuala Lumpur",
    degreeLevel: "UG",
    fields: ["Business", "Engineering", "Arts"],
    meritBased: true,
    needBased: false,
    minGPA: 3.0,
    ieltsMin: 5.5,
    toeflMin: 72,
    coveragePercent: 75,
    amountBDT: 1200000,
    applicationFeeBDT: 1000,
    deadline: new Date('2024-07-20'),
    rolling: false,
    description: "Partial scholarship for international undergraduate students",
    isActive: true
  },
  
  // Japanese Universities
  {
    name: "MEXT Scholarship",
    country: "Japan",
    city: "Tokyo",
    degreeLevel: "Masters",
    fields: ["Engineering", "Science", "Arts"],
    meritBased: true,
    needBased: false,
    minGPA: 3.4,
    ieltsMin: 6.0,
    toeflMin: 79,
    coveragePercent: 100,
    amountBDT: 3500000,
    stipendMonthlyBDT: 110000,
    applicationFeeBDT: 0,
    deadline: new Date('2024-06-30'),
    rolling: false,
    description: "Japanese government scholarship for international students",
    isActive: true
  },
  {
    name: "University of Tokyo PEAK Scholarship",
    country: "Japan",
    city: "Tokyo",
    degreeLevel: "UG",
    fields: ["Science", "Arts", "Engineering"],
    meritBased: true,
    needBased: false,
    minGPA: 3.6,
    ieltsMin: 7.0,
    toeflMin: 100,
    coveragePercent: 100,
    amountBDT: 4200000,
    stipendMonthlyBDT: 130000,
    applicationFeeBDT: 8000,
    deadline: new Date('2024-11-30'),
    rolling: false,
    description: "Full scholarship for English-taught programs",
    isActive: true
  },
  {
    name: "Kyoto University International Scholarship",
    country: "Japan",
    city: "Kyoto",
    degreeLevel: "PhD",
    fields: ["Science", "Engineering", "Medicine"],
    meritBased: true,
    needBased: false,
    minGPA: 3.5,
    ieltsMin: 6.5,
    toeflMin: 88,
    greMin: 310,
    coveragePercent: 100,
    amountBDT: 3800000,
    stipendMonthlyBDT: 125000,
    applicationFeeBDT: 6000,
    deadline: new Date('2024-10-15'),
    rolling: false,
    description: "Full PhD scholarship with research funding",
    isActive: true
  },
  
  // Netherlands Universities
  {
    name: "Holland Scholarship",
    country: "Netherlands",
    city: "Amsterdam",
    degreeLevel: "UG",
    fields: ["Business", "Engineering", "Arts"],
    meritBased: true,
    needBased: false,
    minGPA: 3.3,
    ieltsMin: 6.5,
    toeflMin: 90,
    coveragePercent: 60,
    amountBDT: 2800000,
    applicationFeeBDT: 7000,
    deadline: new Date('2024-05-01'),
    rolling: false,
    description: "Partial scholarship for non-EU international students",
    isActive: true
  },
  {
    name: "TU Delft Excellence Scholarship",
    country: "Netherlands",
    city: "Delft",
    degreeLevel: "Masters",
    fields: ["Engineering", "Technology", "Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.7,
    ieltsMin: 6.5,
    toeflMin: 90,
    coveragePercent: 100,
    amountBDT: 3200000,
    stipendMonthlyBDT: 85000,
    applicationFeeBDT: 5000,
    deadline: new Date('2024-12-01'),
    rolling: false,
    description: "Full scholarship for exceptional engineering students",
    isActive: true
  },
  {
    name: "University of Amsterdam Merit Scholarship",
    country: "Netherlands",
    city: "Amsterdam",
    degreeLevel: "Masters",
    fields: ["Business", "Arts", "Science"],
    meritBased: true,
    needBased: false,
    minGPA: 3.4,
    ieltsMin: 6.5,
    toeflMin: 92,
    coveragePercent: 75,
    amountBDT: 2400000,
    applicationFeeBDT: 4000,
    deadline: new Date('2024-02-01'),
    rolling: false,
    description: "Merit-based scholarship for international master's students",
    isActive: true
  }
];

async function seedScholarships() {
  try {
    console.log('Starting scholarship seeding...');
    
    // Clear existing scholarships
    await Scholarship.deleteMany({});
    console.log('Cleared existing scholarships');
    
    // Get all universities to assign scholarships
    const universities = await University.find({ isActive: true });
    
    if (universities.length === 0) {
      console.log('No universities found. Please seed universities first.');
      return;
    }
    
    console.log(`Found ${universities.length} universities`);
    
    // Additional scholarships to reach 80+ total
    const additionalScholarships = [
      // More Bangladesh scholarships
      {
        name: "Prime Minister's Education Assistance Trust",
        country: "Bangladesh",
        city: "Dhaka",
        degreeLevel: "UG",
        fields: ["Engineering", "Medicine", "Science"],
        meritBased: false,
        needBased: true,
        minGPA: 2.5,
        incomeMaxBDT: 200000,
        coveragePercent: 90,
        amountBDT: 250000,
        stipendMonthlyBDT: 10000,
        applicationFeeBDT: 0,
        rolling: true,
        description: "Government assistance for economically disadvantaged students",
        isActive: true
      },
      {
        name: "Bangladesh Bank Scholarship",
        country: "Bangladesh",
        city: "Dhaka",
        degreeLevel: "Masters",
        fields: ["Business", "Economics", "Finance"],
        meritBased: true,
        needBased: false,
        minGPA: 3.3,
        coveragePercent: 100,
        amountBDT: 400000,
        stipendMonthlyBDT: 20000,
        applicationFeeBDT: 500,
        deadline: new Date('2024-08-30'),
        rolling: false,
        description: "Central bank scholarship for finance students",
        isActive: true
      },
      {
        name: "Chittagong Port Authority Scholarship",
        country: "Bangladesh",
        city: "Chittagong",
        degreeLevel: "UG",
        fields: ["Engineering", "Business", "Maritime Studies"],
        meritBased: true,
        needBased: true,
        minGPA: 3.0,
        incomeMaxBDT: 400000,
        coveragePercent: 75,
        amountBDT: 300000,
        applicationFeeBDT: 1000,
        deadline: new Date('2024-09-15'),
        rolling: false,
        description: "Regional scholarship for port city students",
        isActive: true
      },
      // More Canadian scholarships
      {
        name: "Trudeau Foundation Scholarship",
        country: "Canada",
        city: "Toronto",
        degreeLevel: "PhD",
        fields: ["Social Sciences", "Arts", "Law"],
        meritBased: true,
        needBased: false,
        minGPA: 3.7,
        ieltsMin: 7.0,
        toeflMin: 100,
        coveragePercent: 100,
        amountBDT: 5500000,
        stipendMonthlyBDT: 150000,
        applicationFeeBDT: 10000,
        deadline: new Date('2024-12-01'),
        rolling: false,
        description: "Prestigious PhD scholarship for social sciences",
        isActive: true
      },
      {
        name: "Alberta Graduate Excellence Scholarship",
        country: "Canada",
        city: "Calgary",
        degreeLevel: "Masters",
        fields: ["Engineering", "Energy", "Environment"],
        meritBased: true,
        needBased: false,
        minGPA: 3.5,
        ieltsMin: 6.5,
        toeflMin: 90,
        coveragePercent: 80,
        amountBDT: 2800000,
        applicationFeeBDT: 7000,
        deadline: new Date('2024-10-15'),
        rolling: false,
        description: "Provincial scholarship for graduate studies",
        isActive: true
      },
      {
        name: "Quebec Merit Scholarship for International Students",
        country: "Canada",
        city: "Montreal",
        degreeLevel: "UG",
        fields: ["Arts", "Science", "Engineering"],
        meritBased: true,
        needBased: false,
        minGPA: 3.4,
        ieltsMin: 6.5,
        toeflMin: 88,
        coveragePercent: 70,
        amountBDT: 2500000,
        applicationFeeBDT: 6000,
        deadline: new Date('2024-11-20'),
        rolling: false,
        description: "Provincial merit scholarship for Quebec universities",
        isActive: true
      },
      // More UK scholarships
      {
        name: "Commonwealth Scholarship",
        country: "UK",
        city: "London",
        degreeLevel: "Masters",
        fields: ["Development Studies", "Public Health", "Education"],
        meritBased: true,
        needBased: true,
        minGPA: 3.3,
        incomeMaxBDT: 600000,
        ieltsMin: 6.5,
        toeflMin: 90,
        coveragePercent: 100,
        amountBDT: 4500000,
        stipendMonthlyBDT: 130000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-12-15'),
        rolling: false,
        description: "Commonwealth scholarship for developing country students",
        isActive: true
      },
      {
        name: "Chevening Scholarship",
        country: "UK",
        city: "London",
        degreeLevel: "Masters",
        fields: ["International Relations", "Business", "Law"],
        meritBased: true,
        needBased: false,
        minGPA: 3.5,
        ieltsMin: 6.5,
        toeflMin: 90,
        coveragePercent: 100,
        amountBDT: 5000000,
        stipendMonthlyBDT: 140000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-11-02'),
        rolling: false,
        description: "UK government's global scholarship programme",
        isActive: true
      },
      {
        name: "Gates Cambridge Scholarship",
        country: "UK",
        city: "Cambridge",
        degreeLevel: "PhD",
        fields: ["All Fields"],
        meritBased: true,
        needBased: false,
        minGPA: 3.8,
        ieltsMin: 7.5,
        toeflMin: 110,
        greMin: 320,
        coveragePercent: 100,
        amountBDT: 6500000,
        stipendMonthlyBDT: 180000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-12-03'),
        rolling: false,
        description: "Full scholarship for outstanding applicants from outside the UK",
        isActive: true
      },
      {
        name: "British Council GREAT Scholarship",
        country: "UK",
        city: "Edinburgh",
        degreeLevel: "Masters",
        fields: ["Engineering", "Science", "Arts"],
        meritBased: true,
        needBased: false,
        minGPA: 3.2,
        ieltsMin: 6.5,
        toeflMin: 88,
        coveragePercent: 50,
        amountBDT: 2200000,
        applicationFeeBDT: 5000,
        deadline: new Date('2024-09-30'),
        rolling: false,
        description: "Partial scholarship for selected countries",
        isActive: true
      },
      // More USA scholarships
      {
        name: "Fulbright Foreign Student Program",
        country: "USA",
        city: "New York",
        degreeLevel: "Masters",
        fields: ["All Fields"],
        meritBased: true,
        needBased: false,
        minGPA: 3.5,
        ieltsMin: 7.0,
        toeflMin: 100,
        coveragePercent: 100,
        amountBDT: 6000000,
        stipendMonthlyBDT: 180000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-10-15'),
        rolling: false,
        description: "US government's flagship international exchange program",
        isActive: true
      },
      {
        name: "Yale World Fellows Program",
        country: "USA",
        city: "New Haven",
        degreeLevel: "Masters",
        fields: ["Public Policy", "International Affairs", "Leadership"],
        meritBased: true,
        needBased: false,
        minGPA: 3.7,
        ieltsMin: 7.5,
        toeflMin: 110,
        coveragePercent: 100,
        amountBDT: 7000000,
        stipendMonthlyBDT: 200000,
        applicationFeeBDT: 15000,
        deadline: new Date('2024-12-10'),
        rolling: false,
        description: "Fellowship for emerging global leaders",
        isActive: true
      },
      {
        name: "Princeton International Scholarship",
        country: "USA",
        city: "Princeton",
        degreeLevel: "UG",
        fields: ["Liberal Arts", "Science", "Engineering"],
        meritBased: false,
        needBased: true,
        minGPA: 3.6,
        incomeMaxBDT: 1200000,
        ieltsMin: 7.0,
        toeflMin: 100,
        coveragePercent: 100,
        amountBDT: 7500000,
        stipendMonthlyBDT: 190000,
        applicationFeeBDT: 18000,
        deadline: new Date('2024-11-01'),
        rolling: false,
        description: "Need-based aid for international undergraduates",
        isActive: true
      },
      // More Australian scholarships
      {
        name: "Research Training Program Scholarship",
        country: "Australia",
        city: "Sydney",
        degreeLevel: "PhD",
        fields: ["Science", "Engineering", "Medicine"],
        meritBased: true,
        needBased: false,
        minGPA: 3.5,
        ieltsMin: 6.5,
        toeflMin: 79,
        coveragePercent: 100,
        amountBDT: 4200000,
        stipendMonthlyBDT: 140000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-10-31'),
        rolling: false,
        description: "Government scholarship for research higher degree students",
        isActive: true
      },
      {
        name: "Griffith Remarkable Scholarship",
        country: "Australia",
        city: "Brisbane",
        degreeLevel: "UG",
        fields: ["Business", "Health", "Environment"],
        meritBased: true,
        needBased: false,
        minGPA: 3.3,
        ieltsMin: 6.5,
        toeflMin: 79,
        coveragePercent: 50,
        amountBDT: 2000000,
        applicationFeeBDT: 6000,
        deadline: new Date('2024-08-15'),
        rolling: false,
        description: "Merit scholarship for international undergraduate students",
        isActive: true
      },
      {
        name: "Macquarie University International Scholarship",
        country: "Australia",
        city: "Sydney",
        degreeLevel: "Masters",
        fields: ["Business", "Science", "Arts"],
        meritBased: true,
        needBased: false,
        minGPA: 3.4,
        ieltsMin: 6.5,
        toeflMin: 83,
        coveragePercent: 75,
        amountBDT: 3200000,
        applicationFeeBDT: 7000,
        deadline: new Date('2024-09-30'),
        rolling: false,
        description: "Partial scholarship for international postgraduate students",
        isActive: true
      },
      // More German scholarships
      {
        name: "Heinrich Böll Foundation Scholarship",
        country: "Germany",
        city: "Berlin",
        degreeLevel: "Masters",
        fields: ["Environmental Studies", "Social Sciences", "Arts"],
        meritBased: true,
        needBased: true,
        minGPA: 3.2,
        incomeMaxBDT: 700000,
        ieltsMin: 6.0,
        toeflMin: 80,
        coveragePercent: 100,
        amountBDT: 2800000,
        stipendMonthlyBDT: 85000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-09-01'),
        rolling: false,
        description: "Foundation scholarship for socially engaged students",
        isActive: true
      },
      {
        name: "Friedrich Ebert Foundation Scholarship",
        country: "Germany",
        city: "Munich",
        degreeLevel: "UG",
        fields: ["Social Sciences", "Political Science", "Economics"],
        meritBased: true,
        needBased: true,
        minGPA: 3.0,
        incomeMaxBDT: 600000,
        ieltsMin: 6.0,
        toeflMin: 80,
        coveragePercent: 100,
        amountBDT: 2500000,
        stipendMonthlyBDT: 80000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-07-31'),
        rolling: false,
        description: "Political foundation scholarship for committed students",
        isActive: true
      },
      {
        name: "Max Planck Institute Scholarship",
        country: "Germany",
        city: "Heidelberg",
        degreeLevel: "PhD",
        fields: ["Physics", "Chemistry", "Biology"],
        meritBased: true,
        needBased: false,
        minGPA: 3.8,
        ieltsMin: 6.5,
        toeflMin: 90,
        greMin: 320,
        coveragePercent: 100,
        amountBDT: 4000000,
        stipendMonthlyBDT: 130000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-11-30'),
        rolling: false,
        description: "Research scholarship at prestigious Max Planck Institute",
        isActive: true
      },
      // More Malaysian scholarships
      {
        name: "Malaysia International Scholarship",
        country: "Malaysia",
        city: "Kuala Lumpur",
        degreeLevel: "UG",
        fields: ["Engineering", "Science", "Technology"],
        meritBased: true,
        needBased: false,
        minGPA: 3.2,
        ieltsMin: 6.0,
        toeflMin: 79,
        coveragePercent: 80,
        amountBDT: 1400000,
        applicationFeeBDT: 1500,
        deadline: new Date('2024-08-01'),
        rolling: false,
        description: "Government scholarship for international undergraduate students",
        isActive: true
      },
      {
        name: "Sunway University Merit Scholarship",
        country: "Malaysia",
        city: "Kuala Lumpur",
        degreeLevel: "Masters",
        fields: ["Business", "Hospitality", "Arts"],
        meritBased: true,
        needBased: false,
        minGPA: 3.3,
        ieltsMin: 6.0,
        toeflMin: 79,
        coveragePercent: 60,
        amountBDT: 1200000,
        applicationFeeBDT: 2000,
        deadline: new Date('2024-07-15'),
        rolling: false,
        description: "Private university scholarship for postgraduate students",
        isActive: true
      },
      {
        name: "Taylor's University Excellence Scholarship",
        country: "Malaysia",
        city: "Kuala Lumpur",
        degreeLevel: "UG",
        fields: ["Engineering", "Business", "Design"],
        meritBased: true,
        needBased: false,
        minGPA: 3.5,
        ieltsMin: 6.0,
        toeflMin: 79,
        coveragePercent: 100,
        amountBDT: 1600000,
        stipendMonthlyBDT: 30000,
        applicationFeeBDT: 1000,
        deadline: new Date('2024-06-30'),
        rolling: false,
        description: "Full scholarship for exceptional students",
        isActive: true
      },
      // More Japanese scholarships
      {
        name: "JASSO Scholarship",
        country: "Japan",
        city: "Tokyo",
        degreeLevel: "UG",
        fields: ["All Fields"],
        meritBased: true,
        needBased: false,
        minGPA: 3.0,
        ieltsMin: 6.0,
        toeflMin: 79,
        coveragePercent: 60,
        amountBDT: 2400000,
        stipendMonthlyBDT: 80000,
        applicationFeeBDT: 3000,
        deadline: new Date('2024-05-31'),
        rolling: false,
        description: "Student services organization scholarship",
        isActive: true
      },
      {
        name: "Osaka University International Scholarship",
        country: "Japan",
        city: "Osaka",
        degreeLevel: "Masters",
        fields: ["Engineering", "Medicine", "Science"],
        meritBased: true,
        needBased: false,
        minGPA: 3.4,
        ieltsMin: 6.0,
        toeflMin: 79,
        coveragePercent: 100,
        amountBDT: 3200000,
        stipendMonthlyBDT: 100000,
        applicationFeeBDT: 5000,
        deadline: new Date('2024-08-15'),
        rolling: false,
        description: "Full scholarship for international graduate students",
        isActive: true
      },
      {
        name: "Waseda University Scholarship",
        country: "Japan",
        city: "Tokyo",
        degreeLevel: "PhD",
        fields: ["Social Sciences", "Humanities", "Science"],
        meritBased: true,
        needBased: false,
        minGPA: 3.6,
        ieltsMin: 6.5,
        toeflMin: 88,
        coveragePercent: 100,
        amountBDT: 3600000,
        stipendMonthlyBDT: 120000,
        applicationFeeBDT: 6000,
        deadline: new Date('2024-09-30'),
        rolling: false,
        description: "Doctoral scholarship at prestigious private university",
        isActive: true
      },
      // More Netherlands scholarships
      {
        name: "Orange Tulip Scholarship",
        country: "Netherlands",
        city: "Amsterdam",
        degreeLevel: "Masters",
        fields: ["Business", "Engineering", "Social Sciences"],
        meritBased: true,
        needBased: false,
        minGPA: 3.2,
        ieltsMin: 6.5,
        toeflMin: 90,
        coveragePercent: 50,
        amountBDT: 1800000,
        applicationFeeBDT: 4000,
        deadline: new Date('2024-04-01'),
        rolling: false,
        description: "Scholarship program for selected countries",
        isActive: true
      },
      {
        name: "Erasmus Mundus Joint Master Scholarship",
        country: "Netherlands",
        city: "Delft",
        degreeLevel: "Masters",
        fields: ["Engineering", "Environmental Science", "Technology"],
        meritBased: true,
        needBased: false,
        minGPA: 3.5,
        ieltsMin: 6.5,
        toeflMin: 90,
        coveragePercent: 100,
        amountBDT: 3800000,
        stipendMonthlyBDT: 110000,
        applicationFeeBDT: 0,
        deadline: new Date('2024-01-15'),
        rolling: false,
        description: "EU scholarship for joint master's programs",
        isActive: true
      },
      {
         name: "VU Amsterdam Fellowship Programme",
         country: "Netherlands",
         city: "Amsterdam",
         degreeLevel: "PhD",
         fields: ["Science", "Social Sciences", "Humanities"],
         meritBased: true,
         needBased: false,
         minGPA: 3.6,
         ieltsMin: 6.5,
         toeflMin: 92,
         greMin: 310,
         coveragePercent: 100,
         amountBDT: 3400000,
         stipendMonthlyBDT: 105000,
         applicationFeeBDT: 3000,
         deadline: new Date('2024-11-15'),
         rolling: false,
         description: "PhD fellowship at VU Amsterdam",
         isActive: true
       },
       // Additional scholarships to reach 80+
       {
         name: "Dhaka University Research Grant",
         country: "Bangladesh",
         city: "Dhaka",
         degreeLevel: "PhD",
         fields: ["Science", "Arts", "Social Sciences"],
         meritBased: true,
         needBased: false,
         minGPA: 3.4,
         coveragePercent: 100,
         amountBDT: 600000,
         stipendMonthlyBDT: 25000,
         applicationFeeBDT: 2000,
         deadline: new Date('2024-10-30'),
         rolling: false,
         description: "Research grant for doctoral students",
         isActive: true
       },
       {
         name: "Chittagong University Merit Award",
         country: "Bangladesh",
         city: "Chittagong",
         degreeLevel: "Masters",
         fields: ["Engineering", "Science", "Business"],
         meritBased: true,
         needBased: false,
         minGPA: 3.2,
         coveragePercent: 60,
         amountBDT: 200000,
         applicationFeeBDT: 1500,
         deadline: new Date('2024-08-20'),
         rolling: false,
         description: "Merit-based award for postgraduate students",
         isActive: true
       },
       {
         name: "Sylhet Agricultural University Scholarship",
         country: "Bangladesh",
         city: "Sylhet",
         degreeLevel: "UG",
         fields: ["Agriculture", "Veterinary Science", "Forestry"],
         meritBased: true,
         needBased: true,
         minGPA: 2.8,
         incomeMaxBDT: 350000,
         coveragePercent: 80,
         amountBDT: 180000,
         stipendMonthlyBDT: 8000,
         applicationFeeBDT: 500,
         rolling: true,
         description: "Agricultural scholarship for rural students",
         isActive: true
       },
       {
         name: "Simon Fraser University International Scholarship",
         country: "Canada",
         city: "Vancouver",
         degreeLevel: "Masters",
         fields: ["Computer Science", "Business", "Arts"],
         meritBased: true,
         needBased: false,
         minGPA: 3.3,
         ieltsMin: 6.5,
         toeflMin: 88,
         coveragePercent: 65,
         amountBDT: 2200000,
         applicationFeeBDT: 6500,
         deadline: new Date('2024-09-15'),
         rolling: false,
         description: "International scholarship for graduate students",
         isActive: true
       },
       {
         name: "Carleton University Excellence Award",
         country: "Canada",
         city: "Ottawa",
         degreeLevel: "UG",
         fields: ["Engineering", "Public Affairs", "Science"],
         meritBased: true,
         needBased: false,
         minGPA: 3.6,
         ieltsMin: 6.5,
         toeflMin: 86,
         coveragePercent: 55,
         amountBDT: 2000000,
         applicationFeeBDT: 7000,
         deadline: new Date('2024-11-10'),
         rolling: false,
         description: "Excellence award for international undergraduates",
         isActive: true
       },
       {
         name: "King's College London Scholarship",
         country: "UK",
         city: "London",
         degreeLevel: "UG",
         fields: ["Medicine", "Law", "Arts"],
         meritBased: true,
         needBased: false,
         minGPA: 3.8,
         ieltsMin: 7.0,
         toeflMin: 100,
         coveragePercent: 60,
         amountBDT: 3000000,
         applicationFeeBDT: 9000,
         deadline: new Date('2024-10-01'),
         rolling: false,
         description: "Prestigious scholarship for high achievers",
         isActive: true
       },
       {
         name: "University of Warwick Chancellor's Scholarship",
         country: "UK",
         city: "Coventry",
         degreeLevel: "Masters",
         fields: ["Business", "Engineering", "Social Sciences"],
         meritBased: true,
         needBased: false,
         minGPA: 3.5,
         ieltsMin: 6.5,
         toeflMin: 92,
         coveragePercent: 100,
         amountBDT: 4000000,
         stipendMonthlyBDT: 120000,
         applicationFeeBDT: 8000,
         deadline: new Date('2024-12-20'),
         rolling: false,
         description: "Full scholarship for exceptional international students",
         isActive: true
       },
       {
         name: "University of Bristol Think Big Scholarship",
         country: "UK",
         city: "Bristol",
         degreeLevel: "UG",
         fields: ["Engineering", "Science", "Arts"],
         meritBased: true,
         needBased: false,
         minGPA: 3.4,
         ieltsMin: 6.5,
         toeflMin: 88,
         coveragePercent: 50,
         amountBDT: 2500000,
         applicationFeeBDT: 7500,
         deadline: new Date('2024-09-20'),
         rolling: false,
         description: "Partial scholarship for ambitious students",
         isActive: true
       },
       {
         name: "Columbia University International Fellowship",
         country: "USA",
         city: "New York",
         degreeLevel: "PhD",
         fields: ["Science", "Engineering", "Social Sciences"],
         meritBased: true,
         needBased: false,
         minGPA: 3.7,
         ieltsMin: 7.0,
         toeflMin: 100,
         greMin: 315,
         coveragePercent: 100,
         amountBDT: 7200000,
         stipendMonthlyBDT: 210000,
         applicationFeeBDT: 16000,
         deadline: new Date('2024-12-15'),
         rolling: false,
         description: "Full PhD fellowship with research funding",
         isActive: true
       },
       {
         name: "University of Chicago Merit Scholarship",
         country: "USA",
         city: "Chicago",
         degreeLevel: "UG",
         fields: ["Economics", "Liberal Arts", "Science"],
         meritBased: true,
         needBased: false,
         minGPA: 3.8,
         ieltsMin: 7.5,
         toeflMin: 110,
         coveragePercent: 100,
         amountBDT: 8000000,
         stipendMonthlyBDT: 180000,
         applicationFeeBDT: 20000,
         deadline: new Date('2024-11-15'),
         rolling: false,
         description: "Full merit scholarship for exceptional students",
         isActive: true
       },
       {
         name: "University of Pennsylvania Global Scholarship",
         country: "USA",
         city: "Philadelphia",
         degreeLevel: "Masters",
         fields: ["Business", "Engineering", "Medicine"],
         meritBased: true,
         needBased: false,
         minGPA: 3.6,
         ieltsMin: 7.0,
         toeflMin: 100,
         coveragePercent: 80,
         amountBDT: 5500000,
         applicationFeeBDT: 14000,
         deadline: new Date('2024-10-20'),
         rolling: false,
         description: "Substantial scholarship for international graduate students",
         isActive: true
       },
       {
         name: "UNSW Sydney International Scholarship",
         country: "Australia",
         city: "Sydney",
         degreeLevel: "UG",
         fields: ["Engineering", "Science", "Business"],
         meritBased: true,
         needBased: false,
         minGPA: 3.5,
         ieltsMin: 6.5,
         toeflMin: 90,
         coveragePercent: 70,
         amountBDT: 3000000,
         applicationFeeBDT: 8000,
         deadline: new Date('2024-09-30'),
         rolling: false,
         description: "Merit scholarship for international undergraduates",
         isActive: true
       },
       {
         name: "University of Queensland Excellence Scholarship",
         country: "Australia",
         city: "Brisbane",
         degreeLevel: "Masters",
         fields: ["Science", "Engineering", "Health"],
         meritBased: true,
         needBased: false,
         minGPA: 3.4,
         ieltsMin: 6.5,
         toeflMin: 87,
         coveragePercent: 50,
         amountBDT: 2400000,
         applicationFeeBDT: 7000,
         deadline: new Date('2024-08-31'),
         rolling: false,
         description: "Partial scholarship for postgraduate students",
         isActive: true
       },
       {
         name: "Deakin University International Scholarship",
         country: "Australia",
         city: "Melbourne",
         degreeLevel: "UG",
         fields: ["Business", "Health", "Arts"],
         meritBased: true,
         needBased: false,
         minGPA: 3.2,
         ieltsMin: 6.0,
         toeflMin: 79,
         coveragePercent: 25,
         amountBDT: 1200000,
         applicationFeeBDT: 5000,
         deadline: new Date('2024-07-15'),
         rolling: false,
         description: "Partial tuition scholarship for international students",
         isActive: true
       },
       {
         name: "RWTH Aachen Excellence Scholarship",
         country: "Germany",
         city: "Aachen",
         degreeLevel: "Masters",
         fields: ["Engineering", "Technology", "Science"],
         meritBased: true,
         needBased: false,
         minGPA: 3.6,
         ieltsMin: 6.5,
         toeflMin: 90,
         coveragePercent: 100,
         amountBDT: 3000000,
         stipendMonthlyBDT: 90000,
         applicationFeeBDT: 4000,
         deadline: new Date('2024-08-15'),
         rolling: false,
         description: "Excellence scholarship for engineering students",
         isActive: true
       },
       {
         name: "University of Stuttgart International Scholarship",
         country: "Germany",
         city: "Stuttgart",
         degreeLevel: "UG",
         fields: ["Engineering", "Architecture", "Science"],
         meritBased: true,
         needBased: false,
         minGPA: 3.3,
         ieltsMin: 6.0,
         toeflMin: 80,
         coveragePercent: 75,
         amountBDT: 2200000,
         applicationFeeBDT: 3500,
         deadline: new Date('2024-07-20'),
         rolling: false,
         description: "International scholarship for technical studies",
         isActive: true
       },
       {
         name: "Multimedia University Scholarship",
         country: "Malaysia",
         city: "Cyberjaya",
         degreeLevel: "UG",
         fields: ["Information Technology", "Engineering", "Business"],
         meritBased: true,
         needBased: false,
         minGPA: 3.1,
         ieltsMin: 5.5,
         toeflMin: 72,
         coveragePercent: 50,
         amountBDT: 800000,
         applicationFeeBDT: 1200,
         deadline: new Date('2024-06-15'),
         rolling: false,
         description: "Technology-focused scholarship for undergraduates",
         isActive: true
       },
       {
         name: "Universiti Putra Malaysia International Scholarship",
         country: "Malaysia",
         city: "Kuala Lumpur",
         degreeLevel: "PhD",
         fields: ["Agriculture", "Science", "Engineering"],
         meritBased: true,
         needBased: false,
         minGPA: 3.5,
         ieltsMin: 6.0,
         toeflMin: 79,
         coveragePercent: 100,
         amountBDT: 2000000,
         stipendMonthlyBDT: 50000,
         applicationFeeBDT: 1000,
         deadline: new Date('2024-10-01'),
         rolling: false,
         description: "Full PhD scholarship with research focus",
         isActive: true
       },
       {
         name: "Hokkaido University International Scholarship",
         country: "Japan",
         city: "Sapporo",
         degreeLevel: "Masters",
         fields: ["Agriculture", "Science", "Engineering"],
         meritBased: true,
         needBased: false,
         minGPA: 3.3,
         ieltsMin: 6.0,
         toeflMin: 79,
         coveragePercent: 80,
         amountBDT: 2800000,
         stipendMonthlyBDT: 90000,
         applicationFeeBDT: 4000,
         deadline: new Date('2024-07-31'),
         rolling: false,
         description: "International scholarship for northern Japan studies",
         isActive: true
       },
       {
         name: "Nagoya University Global 30 Scholarship",
         country: "Japan",
         city: "Nagoya",
         degreeLevel: "UG",
         fields: ["Science", "Engineering", "Liberal Arts"],
         meritBased: true,
         needBased: false,
         minGPA: 3.4,
         ieltsMin: 6.5,
         toeflMin: 88,
         coveragePercent: 100,
         amountBDT: 3800000,
         stipendMonthlyBDT: 110000,
         applicationFeeBDT: 7000,
         deadline: new Date('2024-11-30'),
         rolling: false,
         description: "Full scholarship for English-taught programs",
         isActive: true
       },
       {
         name: "Leiden University Excellence Scholarship",
         country: "Netherlands",
         city: "Leiden",
         degreeLevel: "Masters",
         fields: ["Law", "Social Sciences", "Humanities"],
         meritBased: true,
         needBased: false,
         minGPA: 3.5,
         ieltsMin: 7.0,
         toeflMin: 100,
         coveragePercent: 100,
         amountBDT: 3600000,
         stipendMonthlyBDT: 100000,
         applicationFeeBDT: 5000,
         deadline: new Date('2024-02-01'),
         rolling: false,
         description: "Excellence scholarship for master's programs",
         isActive: true
       },
       {
         name: "Utrecht University Excellence Scholarship",
         country: "Netherlands",
         city: "Utrecht",
         degreeLevel: "UG",
         fields: ["Science", "Social Sciences", "Humanities"],
         meritBased: true,
         needBased: false,
         minGPA: 3.4,
         ieltsMin: 6.5,
         toeflMin: 93,
         coveragePercent: 75,
         amountBDT: 2700000,
         applicationFeeBDT: 6000,
         deadline: new Date('2024-05-01'),
         rolling: false,
         description: "Excellence scholarship for undergraduate programs",
         isActive: true
       }
     ];
    
    // Combine original and additional scholarships
    const allScholarships = [...scholarshipData, ...additionalScholarships];
    
    // Assign university IDs to scholarships
    const scholarshipsWithUniversities = [];
    
    for (const scholarship of allScholarships) {
      // Find matching university by country and city
      const matchingUniversities = universities.filter(uni => 
        uni.country.toLowerCase() === scholarship.country.toLowerCase() &&
        uni.city.toLowerCase() === scholarship.city.toLowerCase()
      );
      
      if (matchingUniversities.length > 0) {
        // Assign to a random matching university
        const randomUni = matchingUniversities[Math.floor(Math.random() * matchingUniversities.length)];
        scholarshipsWithUniversities.push({
          ...scholarship,
          university: randomUni._id
        });
      } else {
        // If no exact match, assign to a random university from the same country
        const countryUniversities = universities.filter(uni => 
          uni.country.toLowerCase() === scholarship.country.toLowerCase()
        );
        
        if (countryUniversities.length > 0) {
          const randomUni = countryUniversities[Math.floor(Math.random() * countryUniversities.length)];
          scholarshipsWithUniversities.push({
            ...scholarship,
            university: randomUni._id
          });
        } else {
          // Last resort: assign to any random university
          const randomUni = universities[Math.floor(Math.random() * universities.length)];
          scholarshipsWithUniversities.push({
            ...scholarship,
            university: randomUni._id
          });
        }
      }
    }
    
    // Insert scholarships
    const insertedScholarships = await Scholarship.insertMany(scholarshipsWithUniversities);
    console.log(`Successfully seeded ${insertedScholarships.length} scholarships`);
    
    // Display summary
    const summary = await Scholarship.aggregate([
      { $match: { isActive: true } },
      {
        $group: {
          _id: {
            country: '$country',
            degreeLevel: '$degreeLevel'
          },
          count: { $sum: 1 }
        }
      },
      { $sort: { '_id.country': 1, '_id.degreeLevel': 1 } }
    ]);
    
    console.log('\nScholarship Summary:');
    summary.forEach(item => {
      console.log(`${item._id.country} - ${item._id.degreeLevel}: ${item.count} scholarships`);
    });
    
    console.log('\nScholarship seeding completed successfully!');
    
  } catch (error) {
    console.error('Error seeding scholarships:', error);
  } finally {
    mongoose.connection.close();
  }
}

seedScholarships();